url:
    group_url: http://127.0.0.1:5700/send_group_msg
    user_url: http://127.0.0.1:5700/send_private_msg
    recall_url: http://127.0.0.1:5700/delete_msg
    ban_url: http://127.0.0.1:5700/set_group_ban

fuck_off: ['你说j2呢???', '不会用别瞎艾特, 滚粗!@#$%', '什么玩意?你看看能help(-h;-help)不?', '???mdzz', '你究竟会不会用啊，小伙计???']

function_keyword: [
    "食用",
    "help",
    "-help",
    "-h",
    "search-forum",
    "py",
    "all-py",
    "天气",
    "show-poc",
    "search-poc",
    "cms",
    "information",
    "system",
    "hardware",
    "industrial",
    "what-cms",
    "web-logic-scan",
    "nmap",
    "poc-search-url",
    "protocols-default",
    "protocols-subnet",
    "protocols-vlan"
]

fuck_reply: [
    '，艾特我干嘛？有事儿说事儿，没事儿滚去日站!!!   /菜刀/菜刀',
    '，别瞎鸡儿艾特我!!!   /呸/呸/呸',
    '，滚粗，白了否恩?!!   /白眼/白眼',
    '，走开，嘤嘤嘤!!!   /讨厌/讨厌',
    '，敲里吗，听见没有!!!   /炸弹/炸弹',
    '，人家用小拳拳锤你胸口，哼!!!   /讨厌/讨厌',
    '，艾特我干啥，我在重构!!!   /努力',
    '，去去去，一边玩儿去，滚蛋!!!   /滚粗',
    '，葫芦娃，葫芦娃，一棵藤上七朵花!!!   /啦啦啦',
    '，干啥小崽子!!!    /哼唧唧',
    '，哪凉快哪待着!!!   /傲娇/傲娇']

ban_word: [
    "ssr",
    "vpn",
    "翻墙",
    "黑产",
    "海洛因",
    "冰毒",
    "摇头丸",
    "暗网",
    "习近平",
    "酸酸乳",
    "gfw"]

abuse_word: [
    "傻逼",
    "傻屌",
    "白痴",
    "狗屎",
    "垃圾",
    "nmsl",
    "mlgb",
    "傻吊",
    "智障",
    "狗日的",
    "儿子",
    "废物",
    "煞笔"]

usage_method: "
* 搜索论坛: @ME search-forum 学习资料\n
* 查询已知Poc：@我 show-poc system\n
* 查询已知Poc：@我 show-poc hardware\n
* TCP端口扫描：@ME nmap www.exploit-db.com\n
* CMS识别：@ME what-cms www.exploit-db.com\n
* CMS漏洞扫描： @ME cms www.exploit-db.com\n
* 信息搜集: @ME information www.exploit-db.com\n
* 系统漏洞扫描： @ME system www.exploit-db.com\n
* 物联网设备安全检测: @ME hardware www.exploit-db.com\n
* 工控安全检测: @ME industrial www.exploit-db.com\n
* 搜索POC： @ME search-poc discuz\n
* 查询可用SSR： @ME py\n
* 查询全部可用SS： @ME all-py\n
* 搜索并使用POC进行安全检测： @ME poc-search-url discuz www.exploit-db.com\n
* Weblogic检测： @ME web-logic-scan 111.200.232.78 3389\n
* 默认子网工控设备扫描：@我 protocols-default 111.200.232.0 1  --> 默认扫描子网 /24 返回第一页查询\n
* 扫描子网工控设备：@我 protocols-subnet 111.200.232.0 24 2  --> 扫描子网 /24 返回第二页查询\n
* 扫描子网工控设备：@我 protocols-subnet 111.200.232.0 16 1  --> 扫描子网段 /16 返回第一页查询\n
* 扫描网段内工控设备：@我 protocols-vlan 111.200.232.77 TO 111.200.234.222 1  --> 扫描网段 返回第一页查询\n
* 查询天气：@我 天气 北京市\n
* 查询天气：@我 天气 朝阳区\n
* 查询天气：@我 天气 Beijing"

function_list: "| 功能列表 |\n
--------------------------------------------------------------\n
* 找骂： 直接@ME\n
* 搜索论坛: @ME search-forum keyword\n
* 查询已知Poc：@ME show-poc keyword(cms;hardware;industrial;system;information)\n
* TCP端口扫描：@ME nmap host\n
* CMS识别：@ME what-cms host\n
* CMS漏洞扫描： @ME cms host\n
* 信息搜集: @ME information host\n
* 系统漏洞扫描： @ME system host\n
* 物联网设备安全检测: @ME hardware host\n
* 工控安全检测: @ME industrial host\n
* 搜索POC： @ME search-poc keywords\n
* 搜索并使用POC进行安全检测： @ME poc-search-url keywords host\n
* Weblogic检测： @ME web-logic-scan ip port\n
* 子网工控设备扫描： @ME protocols-default subnet pge_num\n
* 子网段工控设备扫描： @ME protocols-subnet subnet sub_num(16/24) pge_num\n
* 网段工控设备扫描： @ME protocols-vlan subnet TO subnet 1 pge_num\n
* 查询天气： @ME 天气 ??市(区)\n
* 使用方法： @ME 食用\n
--------------------------------------------------------------"
